apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  user: YXBwdXNlcg== # base64 encoded value of "appuser"
  password: cGFzc3dvcmQxMjM= # base64 encoded value of "password123"
  root-password: MTIzNDU2Nzg=  # base64 encoded value of "12345678"